#! /bin/sh
WEBHOME=/export/web/webserver/apache/share

cd $WEBHOME/htdocs/site
cmd=$*
cmd=`echo "$cmd" |tr "[a-z]" "[A-Z]"`
for db in Sun_Server_Assignments.db
do
	cat $db|
	sed '
	s///g
	s/  */ /g
	s/ 	/	/g
	s/	 /	/g
	s/		*$//
	/^$/d'|
  	nawk  -F"	" '
		BEGIN { FOUND=0; }
		NR == 1  { header=$0; F_NUM=NF; next; }
		{ line=$0 ; $0=toupper($0) }
        	/'"$cmd"'/{ 
			if( FOUND == 0 ) print header
			FOUND=1; split(line,a,"	")
			for(i=1;i<F_NUM;i++) printf "%s\t",a[i]
			printf "%s\n", a[F_NUM]
		}
	' 
done
